apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    uid: openfdd_timescale
    access: proxy
    url: db:5432
    user: postgres
    isDefault: true
    version: 1
    editable: false
    secureJsonData:
      password: postgres
    jsonData:
      database: openfdd
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
