title: "open-fdd"
description: "Config-driven FDD for HVAC â€” YAML rules, pandas, Brick"
baseurl: "/open-fdd"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"

aux_links:
  "GitHub": "https://github.com/bbartling/open-fdd"
  "open-fdd-datalake": "https://github.com/bbartling/open-fdd-datalake"
  "PyPI": "https://pypi.org/project/open-fdd/"

footer_content: "MIT License"
